language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

notifications:
  email:
    - dorireuv@gmail.com

install:
  - pip install nose PyHamcrest
  - python setup.py install

script:
  - nosetests